### ISSUE TITLE
401, fix plz!

### ISSUE THREAD

**Issue by shelllshock** [Re-Diss/MMProBumpBot#2]
<img width="1295" alt="Снимок экрана 2024-07-08 в 18 36 10" src="https://github.com/Re-Diss/MMProBumpBot/assets/172393950/1584bc16-1337-4642-b7d9-84ade486ebd6">

**Comment by Re-Diss** [comment]
fixed, do git pull

**Comment by shelllshock** [comment]
![22](https://github.com/Re-Diss/MMProBumpBot/assets/172393950/45a22546-7ed4-4343-9da4-4751c5dca175)
Снова :(

**Comment by Re-Diss** [comment]
пофиксил

**Comment by Re-Diss** [comment]
fixed
